version: '3'
services:
  app:
    build: ./app
    # command: python3 main.py
    command: gunicorn -w 1 -b 0.0.0.0:8000 main:app
    restart: always
    volumes:
      - ./app:/code
    ports:
      - 127.0.0.1:8001:8000
    env_file:
      - .env.flask
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env.mysql
